export default {
  Categories: [],
  total_page: null,
  per_page: null,
  CategoriesTrash: [],
  CategoryID: null,
  SectionID: null,
  sections: [],
  Brands: [],
  total_Brands: null,
  per_Brands: null,
  BrandID: null,
  Product: [],
  ProductID: null,
  Custome: null,
};
